import "./globals.css";
import { Contextapi } from "./context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Contextapi>{children}</Contextapi>
      </body>
    </html>
  );
}
